### ISSUE TITLE
Leaves and saplings have too much data (excess bandwidth)

### ISSUE THREAD

**Issue by RoyCurtis** [ForestryMC/ForestryMC#552]
## Summary
The leaf and sapling block of every Forestry tree is represented as a tile entity, each with a lot of NBT data relating to their genome. I discovered this caused a problem with my orchard in a Direwolf20 multiplayer server; my area took up to 30 seconds and at least 7MiB (!) of bandwidth to load.

This is a problem for players (like me) with poor internet connectivity; the best I can get is 300kb/s and I have no alternatives. Many other players are also in this situation.

## Details

I discovered the issue on:
* [Direwolf20 1.7.10 1.1.1 pack](https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.1.1)
* Forge 10.13.2.1272
* Forestry 3.4.0.7, Binnies 2.0-pre7
* SMP server with 6GB RAM and low activity

Tested additionally on:
* Minecraft 1.7.10 with Forge 10.13.2.1291 and Opis
* Forestry 3.4.0.7 and forestry_1.7.10-3.5.0.485-unstable.jar
* Single player flatland world

## Investigation
I noticed this issue when my base, which I recently have been growing a lot of Forestry and ExtraTrees trees around, would take up to 30 seconds to "load". By load, I mean the chunks would load around me, but nothing would respond (e.g. opening chests) until 30 seconds later. Using Opis, I was able to determine the cause was network; I was reciving too much data from "S3FPacketCustomPayload". 

[My base looks like this](http://i.imgur.com/Ae7FH0m.jpg). Circled in red are the groups of Forestry trees I have grown; there are at least 20 varieties and maybe more than 500+ leaf and sapling blocks with genome data.

By teleporting from my base, to a Mystcraft world with no Forestry trees, and back, I measured (using Opis) that I recieved approx. **7MiB** of data from "S3FPacketCustomPayload" (for comparison, "S26PacketMapChunkBulk" transmits approx. **2MiB**).

To determine whether the source of this data, and whether this was Forestry or ExtraTrees, I set up a local DW20 server of roughly the same configuration. On a flatland map, I planted many Forestry trees around and then I used MCEdit to copy and paste the trees all over the world. This is what I found:

* By surrounding the area in Forestry trees, [up to 35MiB of data was transmitted upon world load](http://i.imgur.com/aNTmiUl.jpg)
* MCEdit tipped me off to the [large amount of data being stored in the leaf blocks](http://i.imgur.com/AT4jgMU.png)
* MCEdit was very slow to both copy and paste leaf blocks

I repeated the above twice more; first I stripped the server down to just Forestry stable and Opis, then again but for Forestry latest unstable. My findings were similar. For each of these tests, I took a schematic of an area with leaf blocks using MCEdit and investigated the NBT data, to ensure I did not miss any optimizations made since stable release:

* [Screenshot of all three schematics](http://i.imgur.com/lFr8k0z.png)
* I determined that addon mods such as ExtraTrees was not causing the issue
* I found that each tile entity had a lot of [redundant data pertaining to their genome](http://i.imgur.com/qbO9mL8.png)

## Suggestions
I am too unfamiliar with Minecraft's, Forge's or Forestry's codebase to make any specific suggestions. However, based on my findings:

* **Optimizing genome data**: Data pertaining to genome is [verbose and redundant](http://i.imgur.com/qbO9mL8.png). There is a duplication of trait values (IIUC, one represents active and inactive?) and they all use strings. Instead, these traits should be represented as a byte array of trait values, where Forestry could save an "index" of corresponding byte offsets and values in the world save. One idea of what this suggestion might look like: http://i.imgur.com/3bbzgOZ.png
 * Instead of 13 compound tags, the 13 traits of this leaf block are held in a 13 byte array
 * The first byte (or byte 0) represents the "tree" trait, which the index has two values for: Walnut (11, or 0x0B) or Pine (16, or 0x10)
 * The eighth byte (or byte 7) represents the "sappiness" trait, which the index has values from Lowest to Highest
 * The "InactiveGenome" array is empty, which means this leaf block's inactive allele is the same as its active. Else, it would be populated with differing trait values.

* **Redesign leaves as blocks, than TileEntities**: Considering there may be many leaves for a single tree (a Walnut has approx. 300!), I wonder if it would be possible to have leaves as blocks than TEs. This would mean Forestry would need a different way to track what genome or "tree" particular leaf blocks belong to.

* **Keep the genome data server side**: I wonder if all the genome data needs to be transmitted to the client. Instead, Forestry could only send data pertaining to the leaf's type and stage of fruit growth (if any) for rendering purposes.
 * A variation of this idea would be to have leaf blocks have only a single integer value; an index value to a list of alleles Forestry could track. This list would be de-duplicated. An example of what this suggestion might look like: http://i.imgur.com/x7pnfqr.png

* **Non-blocking transmission of data**: If possible, all the data could be sent in a way that does not block the player from interacting with the world (e.g. opening chests), but I am unsure if this is possible with Minecraft's design.

## Workarounds
The only workaround I can think of is not to use Forestry trees, or at least to keep them to a minimum in a given area.

## Final Thoughts
I fear this will be a difficult issue to solve, as it represents a fundamental change to how Forestry is handling its data. To optimize it may require migrating older versions of data to newer.

Sorry for the large write-up, I wanted to provide as much helpful data and insight as possible...

**Comment by leagris** [comment]
Even with a fast internet access, chunks with lots of tile-entities are an issue.

In the specific case of Forestry leaf blocks:
* Most NBT Data can be compressed by (guess) the Netty layer. It has all been replaced by another network API after 1.8. So we may expect some performance improvement there.
* All of the genome tag DATA contains redundant or high entropy. So it has better compression.
* Some NBT tags contains quite long hash IDs strings, thus have low entropy, then very bad compression. These are:
 * owner: id: (full MC UUID)
 * textures: Signature and Value (very long incompressible strings data).

@mezz, Before leaving the 1.7.x versions for 1.8, could you review if these texture NBT tags are really needed, or if they can be replaced by some more clever client rendering code?

I mean: If client side rendering code could determine what texture to apply from genome and fruit maturation, it would cut out all of these textures payload.

**Comment by laz2727** [comment]
1) Genome data is NOT redundant. If you don't know how genetics work, it
doesn't mean that data is redundant.
2) I still mostly agree, but i think packets should be compressed instead
of TE data.

**Comment by SirSengir** [comment]
The genome data is required server-side. It shouldn't be synched to the client, the client only needs to know a few things about the texture to use, colour to apply, growth state, etc. Unless something was changed, only that data should show up on the client, not the genome data tag.

It is not possible to reduce leaves to simple blocks. Without genome data the whole system breaks down.

**Comment by leagris** [comment]
Here is a sample of what is transmitted to client for a single leaf block:

See the alarming size of texture Signature and Value:

It is a very bad idea to send actual texture bits for each leaf block.
Or what is it about?

```yaml
ROOT: (TagCompound)
   Decorative: 0
   FL: 1
   ENC: 0
   RT: 301
   x: -125
   y: 65
   z: 181
   id: forestry.Leaves
   ContainedTree: (TagCompound)
      IsAnalyzed: 1
      Genome: (TagCompound)
         Chromosomes: (TagList)
            (TagCompound)
               Slot: 0
               UID0: forestry.treeLemon
               UID1: forestry.treeLemon
            (TagCompound)
               Slot: 1
               UID0: forestry.growthLightlevel
               UID1: forestry.growthLightlevel
            (TagCompound)
               Slot: 2
               UID0: forestry.heightSmallest
               UID1: forestry.heightSmallest
            (TagCompound)
               Slot: 3
               UID0: forestry.saplingsLower
               UID1: forestry.saplingsLower
            (TagCompound)
               Slot: 4
               UID0: forestry.fruitLemon
               UID1: forestry.fruitLemon
            (TagCompound)
               Slot: 5
               UID0: forestry.yieldLower
               UID1: forestry.yieldLower
            (TagCompound)
               Slot: 6
               UID0: forestry.plantTypeNone
               UID1: forestry.plantTypeNone
            (TagCompound)
               Slot: 7
               UID0: forestry.sappinessAverage
               UID1: forestry.sappinessAverage
            (TagCompound)
               Slot: 8
               UID0: forestry.territoryDefault
               UID1: forestry.territoryDefault
            (TagCompound)
               Slot: 9
               UID0: forestry.leavesNone
               UID1: forestry.leavesNone
            (TagCompound)
               Slot: 10
               UID0: forestry.maturationAverage
               UID1: forestry.maturationAverage
            (TagCompound)
               Slot: 11
               UID0: forestry.i1d
               UID1: forestry.i1d
            (TagCompound)
               Slot: 12
               UID0: forestry.fireproofFalse
               UID1: forestry.fireproofFalse
   owner: (TagCompound)
      Id: 09752aa3-8b9c-4f8f-b04f-5421e799547d
      Name: leagris
      Properties: (TagCompound)
         textures: (TagList)
            (TagCompound)
               Signature: SYXnrlVOdw/CcBHzd22vBLLoGDOOEvFB8A6tgAAN5vnDZwN04TyDT1rbRQDtFonBECEFfbMqofplgfGz8mewMSv2JI0VwYu6gtJwahu3b3Xgr9RuvacNvBYOC1eoenBik6oc5Fmcge8jyQaXesyh+m/Uig8BD+RfmDlS4iTCCtctKmf89v7ZfiJTv1kkIBsN6zPOm1UpZbk2toyEmDAELh1fSpsj+Ua7dRLfKHtbRr2JxW3Ex90CJQG7OH1PEADFvO2kTKp6i80qGbSKBZQlKjCVNNHV0+eXB8IvEK2GCLERFQvHHGanFwyJr1Ag49oTIg/EgwiYGUinxAvP5N5Y2mj8LfnSZj2gSXGds605t24klWqOfe+U8gYz2MmBCk7hXN7edKaCgtviEqMaz/R1cS9K/SzYiaS7edUbh6CVWg8HZeP5WcIGe27yzlhXyEFvDoxasaoim7TcWJ6PqzQrVdHp2BuiT/VbL1xAzcCkCmgsePdAljMWtYwZqlqzGu2FONOd63U3WYHzoQeW/CXVaFCe3lsZOSf4pgmieOsJd7MMNA5CruaQUYfC9lVFy/YzEnHNgTA0wAMO5jvA2oPSqUMF7k5SHlR36JecXXpgCMu1qwSbGCj4Ovt+Mg7SJMAZvVlD2VsKOtmtLP6YHkkRPiJITiXg9ehFYVVO0nWh8Sw=
               Value: eyJ0aW1lc3RhbXAiOjE0MjU1MTIyMzEwNDgsInByb2ZpbGVJZCI6IjA5NzUyYWEzOGI5YzRmOGZiMDRmNTQyMWU3OTk1NDdkIiwicHJvZmlsZU5hbWUiOiJsZWFncmlzIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E3NzU4NDllZDlkZjI2ZTM5OGFlYjNkOGIyNjExMThjNjA4YTEyOTk0YTE1OWJjMWMwMjljMWU3YTgifX19
```

**Comment by leagris** [comment]
Well, given you craft your own custom packets with Tag Data, why not just send rendering involved states only?
The only part needed for client rendering is her from my Lemon tree leave:
```yaml
ROOT:
ROOT: (TagCompound)
   x: -125
   y: 65
   z: 181
   id: forestry.Leaves
   type: forestry.treeLemon
   overlay: (TagCompound)
      type: forestry.fruitLemon
      stage: # some int value range from -1 (no fruit) up to max maturation
```
That's all required to select proper texture and overlay icon for client-side rendering.
You could even get ride of the forestry namespace for even lighter packets.

Requirements:
 * [ ] Method to build render tags for custom packet.
 * [ ] New client-side rendering logic (use new "render" NBT tags instead of back-end raw data)

**Comment by CovertJaguar** [comment]
I seem to recall talking to mezz a couple back about the horrible amount of data that Forestry Tiles send to the client. If I recall correctly, the default Tile Entity handler call writeToNBT to populate the packet.

**Comment by MysteriousAges** [comment]
This isn't limited to just leaf blocks, though they are the worst offender because they can be the most populous. Genome data is synched on any kind of apiary, and on butterfly entities.

As a long-term goal, maybe coming up with a better way to represent genomes that would help reduce the overall size of the data would be a good idea.

**Comment by mezz** [comment]
This is well worth optimizing, thanks for the data everyone.
I can take a deeper look this weekend, I think this should be top priority.

**Comment by mezz** [comment]
Ok that was a nightmare to fix and test, but it should be good now. Leaf updates now look like this:
```yaml
   id: forestry.Leaves (byte)
   x: 0 (short)
   y: 0 (short)
   z: 0 (short)
   fruitColor: ffffff (int)
   UID: treeLemon (string)
   leafState: <hasFruitFlag & isPollinatedFlag> (byte)
```
Much much smaller than before!

From the UID I can get the default template genome and get the rest of the information the client needs to render from there (textures, fruit info, etc).

The NBT on the item is still pretty bulky but it hardly matters since it's not being sent to the client.

Please test and let me know if there are any issues. I tested everything I could think of very carefully, but I touched a lot of code so it's still possible I missed something.

**Comment by mezz** [comment]
Oops didn't mean to close this yet.
TODO: 
 * [ ] Saplings
 * [ ] Butterflies 
 * [ ] anything else with genome data

**Comment by leagris** [comment]
Did not test yet @mezz, though If I remember right, different fruits kind can be on one leaf specie.
I can have Apples on a white willow, lemons on a pine tree, cherry on an Apple Oak leaf...
You can only get default fruit from a default template.
So, is it missing a fruit id?

**Comment by leagris** [comment]
One last question, is it backward compatible with old worlds existing tiles?

**Comment by mezz** [comment]
You're right, I overlooked the fruit type, I will have to fix that.
This change is backward compatible with world leaves, but leaf itemstacks stored in an inventory will have issues.

**Comment by mezz** [comment]
Fixed display of non-default fruit on the client. Thanks @leagris !

```yaml
   id: forestry.Leaves (byte)
   x: 0 (short)
   y: 0 (short)
   z: 0 (short)
   UID: forestry.treeLemon (string)
   leafState: <hasFruitFlag & isPollinatedFlag> (byte)

 if (leafState.hasFruitFlag) {
   fruitColor: ffffff (int)
   fruitAlleleUID: forestry.fruitCherry (string)
 }
```
