### ISSUE TITLE
Socketed machines slower in 4.1

### ISSUE THREAD

**Issue by leagris** [ForestryMC/ForestryMC#936]
Not use it was intended, but Socketed Machines (Centrifuge, Squeezer) are much slower than in Forestry 3.6.

Even with 4 golden electron tubes on an intricate circuit board, processing time is slower than in previous Forestry.

I'd say, these machines should have same speed and energy requirements as there 3.6 counterpart when non equipped with circuits.

Aside of this: A mean to configure these machines base speed would be a nice addition.

**Comment by mezz** [comment]
Thanks for the report!
That is definitely not intentional. The code changes internally were pretty major to support the sockets, so I need to fix the speed to match the old one. 

A configuration should be possible with this new code as well.

If you have information about what it should be, that would be helpful. I'm going to open up my 3.6 world and do some speed comparison testing.

**Comment by mezz** [comment]
Test results:

Squeezer:
40 RF/t
2000 RF per drop

Centrifuge:
30 RF/t
3200 RF per comb

**Comment by leagris** [comment]
Could you also look at the carpenter code?
While the carpenter does not have socket, in 4.1 it takes a lot more time to craft EG a Scented panel.

**Comment by mezz** [comment]
Carpenter:
40 RF/t
10,200 RF per scented panel

Bottler:
40 RF/t
1000 RF per can

Analyzer:
20,320 RF per bee
32 RF/t

Fermenter:
4,200 RF / sapling + water
120 RF/t

Still:
20,200 RF / biomass bucket
40 RF/t

**Comment by mezz** [comment]
Should all be fixed in the latest build. Please try it out and see if you find anything unusual.

**Comment by leagris** [comment]
Awesome.
I test this ASAP when build 791 is up on CI.
For now it is still build 790 from yesterday.

**Comment by mezz** [comment]
Ok I think Jenkins was down when I pushed the change. Should be up now.

**Comment by leagris** [comment]
From first test, it look like socket upgrades are not working.

I have absolutely no boost on speed with example Centrifuge.

Centrifuge1: (intricate circuit with 4 blazing electron tubes)

``` yaml
sockets: (TagList)
  (TagCompound)
     Count: 1
     Slot: 0
     Damage: 3
     id: 4513
     tag: (TagCompound)
        T: 3
        CA.I0: forestry.machine.speed.boost.2
        CA.I1: forestry.machine.speed.boost.2
        CA.I2: forestry.machine.speed.boost.2
        CA.I3: forestry.machine.speed.boost.2
        LY: forestry.machine.upgrade
```

Centrifuge2: (intricate circuit with 2 blazing electron tubes and 2 golden electron tubes)

``` yaml
sockets: (TagList)
  (TagCompound)
     Count: 1
     Slot: 0
     Damage: 3
     id: 4513
     tag: (TagCompound)
        T: 3
        CA.I0: forestry.machine.efficiency.1
        CA.I1: forestry.machine.efficiency.1
        CA.I2: forestry.machine.speed.boost.2
        CA.I3: forestry.machine.speed.boost.2
        LY: forestry.machine.upgrade
```

Centrifuge3: (empty socket)

``` yaml
sockets: (TagList)
```

There is absolutely no difference in speed or energy usage.
